package com.example.aspblindajes.model;

public enum MovementType {
    LOGISTIC_CHECKIN, LOGISITIC_CHECKOUT, PRODUCTION_CHECKIN, PRODUCTION_CHECKOUT, LOGISTIC_RECHECKIN, LOGISTIC_CHECKOUT_TO_CLIENT
}
